#!/usr/bin/env bash
set -euo pipefail

if [[ -z "${CONDA_PREFIX:-}" ]]; then
  echo "ERROR: Activate the IIBacFinder conda environment before running this script." >&2
  exit 1
fi

ACTIVATE_DIR="$CONDA_PREFIX/etc/conda/activate.d"
DEACTIVATE_DIR="$CONDA_PREFIX/etc/conda/deactivate.d"
mkdir -p "$ACTIVATE_DIR" "$DEACTIVATE_DIR"

cat > "$ACTIVATE_DIR/iibacfinder_ld_library_path.sh" <<'EOF'
# Generated by IIBacFinder: prefer the conda environment's C++ runtime.
if [[ -n "${LD_LIBRARY_PATH:-}" ]]; then
  export IIBACFINDER_LD_LIBRARY_PATH_BACKUP="$LD_LIBRARY_PATH"
else
  unset IIBACFINDER_LD_LIBRARY_PATH_BACKUP
fi
export LD_LIBRARY_PATH="$CONDA_PREFIX/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
EOF

cat > "$DEACTIVATE_DIR/iibacfinder_ld_library_path.sh" <<'EOF'
# Restore the LD_LIBRARY_PATH value that existed before IIBacFinder activation.
if [[ -n "${IIBACFINDER_LD_LIBRARY_PATH_BACKUP:-}" ]]; then
  export LD_LIBRARY_PATH="$IIBACFINDER_LD_LIBRARY_PATH_BACKUP"
else
  unset LD_LIBRARY_PATH
fi
unset IIBACFINDER_LD_LIBRARY_PATH_BACKUP
EOF

echo "Installed conda activation hooks in:"
echo "  $ACTIVATE_DIR/iibacfinder_ld_library_path.sh"
echo "  $DEACTIVATE_DIR/iibacfinder_ld_library_path.sh"
echo "Run 'conda deactivate && conda activate IIBacFinder' to activate the hook."
